### ISSUE TITLE
Support for DataTables (fix coming in Cucumber 2.3.3+ )

### ISSUE THREAD

**Issue by tk8817** [rajatthareja/ReportBuilder#10]
Hey @rajatthareja,

The cucumber dev's just closed a ticket of mine where inline data tables were not being sent to the JSON report. This was broken since Cucumber 2.1. The have pushed a fix to master, but not yet released. 

To fully understand the matter, please see my ticket here: https://github.com/cucumber/cucumber-ruby/issues/948

Once the fix is released we should be prepared to correctly handle/display this new data in the HTML report.

**Comment by rajatthareja** [comment]
Support for Data Tables added as per format specified in cucumber/cucumber-ruby#948

**Comment by tk8817** [comment]
Thanks @rajatthareja
