### ISSUE TITLE
ERB.new error

### ISSUE THREAD

**Issue by joohwho** [rajatthareja/ReportBuilder#105]
Errors:
![image](https://user-images.githubusercontent.com/95352162/170707594-f83cc581-e76d-4db2-8e33-2ac9876b1270.png)
![image](https://user-images.githubusercontent.com/95352162/170707649-fd132a07-f35c-42dc-a955-3f24e8f18af3.png)

Ruby version: 
![image](https://user-images.githubusercontent.com/95352162/170707756-3742ed57-4234-40ff-9c61-e2b1eb4b1738.png)

**Comment by joohwho** [comment]
I fixed like this, but I don't know if is correct [LOL]:


![image](https://user-images.githubusercontent.com/95352162/170714849-bc2ec370-247a-46b5-b7bd-dca91fcd49e6.png)

**Comment by parradox-2nd** [comment]
Your fix worked for me.  It looks like the repo is very stale though, so I don't know if this will ever make it in to the main gem :(

**Comment by phebus** [comment]
fwiw i put in a PR for this. but not sure if it'll get merged. might have to start building from my fork https://github.com/rajatthareja/ReportBuilder/pull/106

**Comment by enkessler** [comment]
Fixed by #106
