### ISSUE TITLE
undefined method `merge!'

### ISSUE THREAD

**Issue by nicothyrael** [rajatthareja/ReportBuilder#13]
Hi, I can't make it work, always get:
report_builder.rb:83:in `build_report': undefined method `merge!' for nil:NilClass (NoMethodError)

$ ruby -v
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]

$ cucumber --version
2.3.2

I tried with rubygems repository, with git repository and nothing.
Can you help me please?

Thanks!

**Comment by tk8817** [comment]
Hi @nicothyrael , can you please post the code you are using to instantiate ReportBuilder. We can get you up and running easily, I recommend setting everything in the config block:

```ruby
    ReportBuilder.configure do |config|
      config.json_path = 'cucumber_sample/logs'
      config.report_path = 'sample_report'
      config.report_types = [:json, :html]
      config.report_tabs = [:overview, :features, :scenarios, :errors]
      config.compress_images = false
    end

    ReportBuilder.build_report
```

**Comment by nicothyrael** [comment]
I use that same code and get the error too.
Let me know what else I can share with you to help.
Or steps to try.

**Comment by tk8817** [comment]
@nicothyrael - if you are using that exact code, then we have found your problem. It is sample code and needs to be updated to your environment. 

We can only help as much as what we have to work with. If you can please post a code snippet & some logs with details of what you are trying to accomplish - I am sure we can solve your issue.. In my prior post I asked the reason for using ruby 1.9, that would be a good place to start.

**Comment by tk8817** [comment]
@nicothyrael , if I had to guess, I would say the input you are passing is malformed and as such is being treated as a nil reference. The line of code you are failing on is evaluating the input parameters

```ruby
    @options.merge! options if options.is_a? Hash
```

**Comment by tk8817** [comment]
@nicothyrael please close this issue if things are working well for you.

**Comment by nicothyrael** [comment]
Hi,
I'm using that version of Ruby because the CI server has it too.
I'm calling ReportBuilder from a rake task created as your documentation:

desc 'Rake task to build report'
task :report_builder, [:json_path, :report_path, :report_types, :report_tabs, :compress_images] do |t, args|
  args.with_defaults(:json_path => nil, :report_path => 'test_report', :report_types => [:html], :report_tabs => [:overview, :features, :errors], :compress_images => false)
  options = {:json_path => args.json_path, :report_path => args.report_path, :report_types => args.report_types, :report_tabs => args.report_tabs, :compress_images => args.compress_images}
  ReportBuilder.build_report options
end


nicolas.alonso@AR-IT02585 MINGW64 ~/Documents/LRES Service (master)
$ rake report_builder ['cucumber_sample/logs/'] --trace
** Invoke report_builder (first_time)
** Execute report_builder
rake aborted!
NoMethodError: undefined method `merge!' for nil:NilClass
C:/Ruby193/lib/ruby/gems/1.9.1/gems/report_builder-0.0.9/lib/report_builder.rb:83:in `build_report'
C:/Users/nicolas.alonso/Documents/LRES Service/Rakefile:45:in `block in <top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/Ruby193/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
C:/Ruby193/bin/rake:23:in `load'
C:/Ruby193/bin/rake:23:in `<main>'
Tasks: TOP => report_builder

**Comment by nicothyrael** [comment]
I'm still have the issue, it's not solved.

**Comment by tk8817** [comment]
Hey @nicothyrael, 

Please try using the absolute path in your rake call, from what I can see ReportBuilder is not able to detect any json files in the partial directory your are sending it and as such, nil is being sent along the line. 

Windows might be the culprit here, however - Rajat or I could work on hardening the file loading to do explicit path expansion if required.

**Comment by nicothyrael** [comment]
Ok, I tried, same result:

nicolas.alonso@AR-IT02585 MINGW64 ~/Documents/LRES Service (master)
$ rake report_builder ['c:/Users/nicolas.alonso/Documents/LRES Service/cucumber_sample/logs'/] --trace
** Invoke report_builder (first_time)
** Execute report_builder
rake aborted!
NoMethodError: undefined method `merge!' for nil:NilClass
C:/Ruby193/lib/ruby/gems/1.9.1/gems/report_builder-0.0.9/lib/report_builder.rb:83:in `build_report'
C:/Users/nicolas.alonso/Documents/LRES Service/Rakefile:45:in `block in <top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/Ruby193/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
C:/Ruby193/bin/rake:23:in `load'
C:/Ruby193/bin/rake:23:in `<main>'
Tasks: TOP => report_builder

**Comment by tk8817** [comment]
Hi @nicothyrael , your trailing backslash is outside of the string in the code pasted above

```ruby
$ rake report_builder ['c:/Users/nicolas.alonso/Documents/LRES Service/cucumber_sample/logs'/] --trace
** Invoke report_builder (first_time)
** Execute report_builder
rake aborted!
```

**Comment by nicothyrael** [comment]
Sorry, tested again, same error:

nicolas.alonso@AR-IT02585 MINGW64 ~/Documents/LRES Service (master)
$ rake report_builder ['c:/Users/nicolas.alonso/Documents/LRES Service/cucumber_sample/logs/'] --trace
** Invoke report_builder (first_time)
** Execute report_builder
rake aborted!
NoMethodError: undefined method `merge!' for nil:NilClass
C:/Ruby193/lib/ruby/gems/1.9.1/gems/report_builder-0.0.9/lib/report_builder.rb:83:in `build_report'
C:/Users/nicolas.alonso/Documents/LRES Service/Rakefile:45:in `block in <top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/Ruby193/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
C:/Ruby193/bin/rake:23:in `load'
C:/Ruby193/bin/rake:23:in `<main>'
Tasks: TOP => report_builder

**Comment by tk8817** [comment]
@nicothyrael please also loop in my other advice to escape the spaces in your path name. For an easier test, try using a path without spaces in it. I am also a little unsure on the path you are providing, try using escaped backslashes instead of forward slashes:

https://www.ruby-forum.com/topic/1448441

reading thorough that thread I noticed a person showed how Windows paths are not picked up if not written in a very specific fashion

```ruby
It's the way Ruby handles your strings. You are using double quotes,
so you need to escape the backslash. If you use single quotes, you can
use the single backslash. Look at the following:

 irb(main):001:0> File.directory? "C:"
 => true
 irb(main):002:0> File.directory? "C:\Users"
 => false
 irb(main):003:0> File.directory? "C:\\Users"
 => true
 irb(main):004:0> File.directory? 'C:\Users'
 => true
```

**Comment by nicothyrael** [comment]
Ok, just moved the folder and tested with your suggestions, doesn't work.

nicolas.alonso@AR-IT02585 MINGW64 ~/Documents/LRES Service (master)
$ rake report_builder ['c:\\cucumber_sample\\logs\\'] --trace
** Invoke report_builder (first_time)
** Execute report_builder
rake aborted!
NoMethodError: undefined method `merge!' for nil:NilClass

nicolas.alonso@AR-IT02585 MINGW64 ~/Documents/LRES Service (master)
$ rake report_builder ['c://cucumber_sample//logs//'] --trace
** Invoke report_builder (first_time)
** Execute report_builder
rake aborted!
NoMethodError: undefined method `merge!' for nil:NilClass

(used one slash/backslash at the end too, same results)

**Comment by tk8817** [comment]
@rajatthareja , any thoughts here. I still think this is a pathing issue. 
@nicothyrael , try updating the default value in the rake script -- this will ensure you don't get a null response. I have provided the code below

```ruby
desc 'Rake task to build report'
task :report_builder, [:json_path, :report_path, :report_types, :report_tabs, :compress_images] do |t, args|
  args.with_defaults(:json_path => 'C:\cucumber_sample\logs', :report_path => 'test_report', :report_types => [:html], :report_tabs => [:overview, :features, :errors], :compress_images => false)
  options = {:json_path => args.json_path, :report_path => args.report_path, :report_types => args.report_types, :report_tabs => args.report_tabs, :compress_images => args.compress_images}
  ReportBuilder.build_report options
end
```

**Comment by rajatthareja** [comment]
lib/report_builder.rb:65 
@options = default_options.to_h
OpenStruct is not getting converted to Hash

OpenStruct#to_h is not available in Ruby 1.9.1

Replaced "to_h" to "marshal_dump"
@options = default_options.marshal_dump

Committed fix in master.

**Comment by tk8817** [comment]
@nicothyrael -- rajat nailed the issue, get the latest master (instead of pulling directly from rubygems)

```ruby
gem 'report_builder', github: 'rajatthareja/ReportBuilder'
```

We will make a rubygems release soon. I would suggest upgrading from Ruby 1.9 as well, lots of libs are dropping support (or already have).

**Comment by nicothyrael** [comment]
Thanks, testing it get: LoadError: cannot load such file -- report_builder

Yes, I know, but it's not my choice to make. I will give the IT guys the suggestion.

**Comment by nicothyrael** [comment]
Only works without a path, if the json file it's in the same folder as the Rakefile.

**Comment by rajatthareja** [comment]
Please remove space between "report_builder" and "[" and try again.
Ex: 
change this
rake report_builder ['path/of/json/files/dir'] to
rake report_builder['path/of/json/files/dir']

**Comment by nicothyrael** [comment]
I get: ReportBuilderParsingError

rake report_builder['report/'] --trace

Same with //

But works ok with full path:

$ rake report_builder['c:/cucumber_sample/logs/'] --trace
** Invoke report_builder (first_time)
** Execute report_builder
HTML test report generated: 'test_report.html'

How I can make it work inside the proyect folder with no full paths?

**Comment by rajatthareja** [comment]
cucumber version?

**Comment by nicothyrael** [comment]
$ cucumber --version
2.3.2

**Comment by rajatthareja** [comment]
It will be very helpful if you could please share your JSON files.

**Comment by nicothyrael** [comment]
I just renamed it to .txt to be uploaded here.
[logs.txt](https://github.com/rajatthareja/ReportBuilder/files/148655/logs.txt)

**Comment by rajatthareja** [comment]
$ ls log
logs.json

$ rake report_builder['log/'] --trace
** Invoke report_builder (first_time)
** Execute report_builder
HTML test report generated: 'test_report.html'

![test results](https://cloud.githubusercontent.com/assets/16877986/13361799/d367e192-dce6-11e5-9a92-f9b1e7110b7e.png)

Working fine for me verified in MAC and Windows.

**Comment by nicothyrael** [comment]
Tested again and it's working.
THANKS !!!!!!!!!

**Comment by tk8817** [comment]
@nicothyrael Wooooo, glad we could help you out. Enjoy the library, it is pretty kick ass.
