### ISSUE TITLE
Report Improvements - Add Ability to Pass Env Variables To Report

### ISSUE THREAD

**Issue by mglaze** [rajatthareja/ReportBuilder#15]
We have several environments where we run our tests, it would be great to have the ability to pass Env Variables to the report. We'd like to include build number, git branch, environment, browser, etc to the header. So at first glance anyone looking at the report will know where the tests ran.

Mockup: 
![image](https://cloud.githubusercontent.com/assets/1659393/13467924/68a5c0e6-e06e-11e5-8628-eca811ca6dd5.png)

**Comment by rajatthareja** [comment]
Added support for additional info, now you can pass additional info to  ReportBuilder

```ruby
options = { 
  additional_info: {environment: 'Stage 5', browser: ENV['browser'], 'build' => 1980}
}
```

```ruby
ReportBuilder.configure do |config|
 config.additional_info = {environment: 'Stage 5', browser: ENV['browser'], 'build' => '#1980'}
end
```

![title](https://cloud.githubusercontent.com/assets/16877986/13494372/c6e7af24-e169-11e5-9d8b-b589a4b18a78.png)

**Comment by tk8817** [comment]
How's that for turnaround time @mglaze :)

**Comment by mglaze** [comment]
Look at that! You guys rock.
