### ISSUE TITLE
Hide features that don't have scenarios with matching tags

### ISSUE THREAD

**Issue by tk8817** [rajatthareja/ReportBuilder#18]
Hey @rajatthareja When using the tag dropdown on the features tab, we should hide any features which do not have at least one scenario inside with a matching tag. I think it gives the wrong impression in the current design.

**Comment by rajatthareja** [comment]
Updated java script. https://github.com/rajatthareja/ReportBuilder/commit/7b700e68046af5819ca74615c6b8f993512e7178

**Comment by tk8817** [comment]
Thanks @rajatthareja
