### ISSUE TITLE
Feature status = 'Unknown' when a Scenario is marked 'Pending'

### ISSUE THREAD

**Issue by tk8817** [rajatthareja/ReportBuilder#19]
Right now when you run a set of tests and a feature contains a scenario which is marked 'pending' the overall feature status is labeled as 'Unknown'. I think we should re-design this to show the feature as 'in-progress' or 'incomplete'

**Comment by rajatthareja** [comment]
Replaced 'unknown' with 'incomplete'. https://github.com/rajatthareja/ReportBuilder/commit/484c94eb4ca353dc566cb18090c66cbba5e64a82

**Comment by tk8817** [comment]
Thanks @rajatthareja
