### ISSUE TITLE
[styling] Alphabetize Features on Features Tab

### ISSUE THREAD

**Issue by mglaze** [rajatthareja/ReportBuilder#20]
Would be nice to have the features alphabetized on the features tab for easy file location.

**Comment by rajatthareja** [comment]
Features alphabetized on features tab https://github.com/rajatthareja/ReportBuilder/commit/bc9d0c557c6321f1bc4871379b5af16644210a55 and scenarios alphabetized on scenarios tab. https://github.com/rajatthareja/ReportBuilder/commit/8d52cc212f65ff2563049fdd351c6001de3648ea

**Comment by mglaze** [comment]
:+1: Thanks!
