### ISSUE TITLE
Make a Gitter room to discuss updates

### ISSUE THREAD

**Issue by tk8817** [rajatthareja/ReportBuilder#21]

**Comment by rajatthareja** [comment]
[![Join the chat at https://gitter.im/rajatthareja/ReportBuilder](https://badges.gitter.im/rajatthareja/ReportBuilder.svg)](https://gitter.im/rajatthareja/ReportBuilder?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
