### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by nbouhid** [rajatthareja/ReportBuilder#26]
Hello, first of all, very nice plugin!!

I just can't get it to work. I'm trying to use it in order to have all the different reports inside the same file generated using the parallel_cucumber plugin.

For some reason, when executing it:

`report_builder -s "reports/123/report-1.json,reports/123/report-2.json" -f html`

I'm getting this error and I can't understand what is that about:

```
/var/lib/gems/2.2.0/gems/report_builder-0.1.2/lib/report_builder.rb:100:in `rescue in build_report': ReportBuilderParsingError (RuntimeError)
    from /var/lib/gems/2.2.0/gems/report_builder-0.1.2/lib/report_builder.rb:100:in `build_report'
    from /var/lib/gems/2.2.0/gems/report_builder-0.1.2/bin/report_builder:66:in `<top (required)>'
    from /usr/local/bin/report_builder:23:in `load'
    from /usr/local/bin/report_builder:23:in `<main>'

```

Do you know what could be causing this issue?

Thanks!

**Comment by rajatthareja** [comment]
Hello,

Please share sample json reports. You can sent it to me at mail@rajatthareja.com
Also let me know you cucumber and ruby version.

Regards,
Rajat

**Comment by nbouhid** [comment]
Hello, my cucumber version is 2.3.3 and ruby version 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux-gnu]

Thanks!

**Comment by rKrums** [comment]
I'm having the same issue. I know that £ symbol is causing this. Encoding of all files is set to UTF-8, but after the error stacktrace, I see

` "\xC2" on US-ASCII"\xC2" on US-ASCII"\xC2" on US-ASCII"\xC2" on US-ASCII`

**Comment by slapresta** [comment]
https://github.com/rajatthareja/ReportBuilder/issues/27#issuecomment-267576029 This can be relevant to your problem.

**Comment by rajatthareja** [comment]
https://github.com/rajatthareja/ReportBuilder/commit/ff9f83c6c2eb01ca155a59e386df25e1344beb77
