### ISSUE TITLE
Not handling well special characters

### ISSUE THREAD

**Issue by m-velasquez** [rajatthareja/ReportBuilder#27]
I have this special character in a json file: "–"
The report is showing like: ΓÇô

Could you please take a look on this?
Thank you in advance.

**Comment by marcoHub** [comment]
Any updates regarding the special character?

Thank you.

**Comment by slapresta** [comment]
@marcoHub This is an encoding problem; the JSON generated by Cucumber is UTF-8 encoded, but your machine interprets it as some other encoding.

Try prepending `LC_ALL=C.UTF-8` to your report_builder invocation, as in: `LC_ALL=C.UTF-8 report_builder -s ... -o ...`

**Comment by rajatthareja** [comment]
https://github.com/rajatthareja/ReportBuilder/commit/ff9f83c6c2eb01ca155a59e386df25e1344beb77
