### ISSUE TITLE
Support for saving/exporting the combined JSON file

### ISSUE THREAD

**Issue by tk8817** [rajatthareja/ReportBuilder#3]
Hey, 

This is a fantastic gem but I think one key part which is missing is the ability to export / save the combined JSON such that you can use it elsewhere. In fact, this gem is currently one of the best JSON combiners for cucumber.

**Comment by rajatthareja** [comment]
Added support for combined JSON file.
Output file format html or json or both

```ruby
    ReportBuilder.build_report('path/of/json/files/dir','my_test_report_name','json_html')
    ReportBuilder.build_report('path/of/json/files/dir','my_test_report_name','json')
    ReportBuilder.build_report('path/of/json/files/dir','my_test_report_name','html')
```

**Comment by prashanth-sams** [comment]
@rajatthareja the latest version is not supporting these additional options

**Comment by rajatthareja** [comment]
@prashanth-sams Please refer to latest docs https://github.com/rajatthareja/ReportBuilder#config-options and raise a new issue with more details if required.
