### ISSUE TITLE
issues with fixnum

### ISSUE THREAD

**Issue by sofiawan** [rajatthareja/ReportBuilder#30]
I met this issues when try to run the report builder

NoMethodError: undefined method `gsub' for 1:Fixnum

seems there's some fixnum in output string block the process

after i add a '.to_s' to line328 at report_builder.rb

 def self.build_output(outputs)
    outputs.each do |output|
      @builder << "<span style='color:#{COLOR[:output]}'>#{output.to_s.gsub("\n",'</br>').gsub("\t",'&nbsp;&nbsp;').gsub(' ','&nbsp;')}</span><br/>"
    end if outputs.is_a?(Array)
  end

it works fine

how can i save this change on my own project

**Comment by rajatthareja** [comment]
Please create a Pull request for the fix

**Comment by rajatthareja** [comment]
Working fine now. Hence closing.
