### ISSUE TITLE
Passing all Json from different folder

### ISSUE THREAD

**Issue by hanikad** [rajatthareja/ReportBuilder#31]
IS it possible to enhance report builder based on folder and create dashboard accordingly.

For eg:

If i have function a -which has 3 json
Functionality b- which has 3 json

Can i get master dashboard with functionality and no.of test than at feature level

**Comment by rajatthareja** [comment]
**Now we can group features.**

**[Sample Report](http://reportbuilder.rajatthareja.com/sample/group_report.html)**

**[Sample Code](http://reportbuilder.rajatthareja.com/#grouped-features-report-example)**
