### ISSUE TITLE
Roadmap for Gem?

### ISSUE THREAD

**Issue by cheezy** [rajatthareja/ReportBuilder#38]
@rajatthareja are you still working on this gem?  If so, what changes do you hope to make?

**Comment by tk8817** [comment]
@cheezy - I co-maintain this with @rajatthareja, however neither of us have any features planned at this time. Both of us are using alternate solutions day to day now.

**Comment by cheezy** [comment]
@tk8817 are you using a different report gem or a different approach to reporting?

**Comment by cheezy** [comment]
I have created a fork and I hope to make a few enhancements.  First of all I am going to get tests around the gem while I refactor it to a more object oriented style.  Next I hope to add the more customizable report.  Are you guys interested in these changes?

**Comment by tk8817** [comment]
@cheezy - we have adopted a test management system (JIRA Adaptavist Test Management) and wrote a set of bindings + RSpec formatter to get results from our test runs into it. 

I would be happy to add you as a maintainer of this gem, if you think it makes sense. Otherwise, we would be happy to accept PR's to improve design / testability / features.

**Comment by enkessler** [comment]
@tk8817 @cheezy I've also taken a crack at this and have at least one more PR ready to go if these kinds of changes are going to happen.

**Comment by enkessler** [comment]
My PRs are in.

I didn't want to be too disruptive so I've kept things backwards compatible. That being said, I'd be just as inclined to redesign the thing as @cheezy is.

**Comment by tk8817** [comment]
@cheezy / @enkessler , I will give it a few more days - but I have been unable to reach @rajatthareja even on his personal email. I would advise that we fork and start by brining in @enkessler's PR's and then move toward @cheezy's vision. 

I will touch base on Wednesday.

**Comment by rajatthareja** [comment]
Hi All,

@cheezy  @enkessler 

All enhancements are most welcome.

@tk8817 Thanks for updating me through email.

I was busy with some other stuff from last few months.

From now, I will keep track of all request on daily basis and will release a new version of gem on rubygem.org weekly if we have any changes.

Keep up all good work. Let's make reporting better and easier together.

**Comment by cheezy** [comment]
I hope to start to make small changes that will pull the large files into their individual classes first. Once I finish this I hope to refactor the classes a little while I add specs.  Are you guys good with these changes?

**Comment by cheezy** [comment]
Which git repo will we use?  Stay with this one?

**Comment by rajatthareja** [comment]
@cheezy It sounds good to me.

**Comment by cheezy** [comment]
Just pushed the start of those changes.

**Comment by cheezy** [comment]
How do you guys feel about a refactoring that moves all of the HTML/Javascript out of the code and into ERBs?

**Comment by enkessler** [comment]
A dynamically filled in template beats a cobbled together string, so I'm all for it. Separation of concerns for the win!

**Comment by rajatthareja** [comment]
Done major refactor new UI, ERB etc. 
[Sample Report](http://rajatthareja.github.io/ReportBuilder/)

@cheezy @enkessler @tk8817 
Please have a look and let me know if I break anything or any enhancements required.
