### ISSUE TITLE
Getting Encoding Issue

### ISSUE THREAD

**Issue by dkjha52** [rajatthareja/ReportBuilder#42]
Getting below output - 
---------------------------
Link embedding skipped!
Encoding::UndefinedConversionError
"\xC2" from ASCII-8BIT to UTF-8
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/xmlmarkup.rb:281:in `write'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/xmlmarkup.rb:281:in `<<'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/xmlmarkup.rb:281:in `_text'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:118:in `<<'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/report_builder-0.1.4/lib/report_builder.rb:433:in `block (2 levels) in build_embedding'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:175:in `_nested_structures'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:68:in `tag!'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/report_builder-0.1.4/lib/report_builder.rb:432:in `block in build_embedding'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/report_builder-0.1.4/lib/report_builder.rb:401:in `each'
/Users/home/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/report_builder-0.1.4/lib/report_builder.rb:401:in `build_embedding'
Link embedding skipped!
-------------------------
Please let me know how I will override this error

**Comment by rajatthareja** [comment]
https://github.com/rajatthareja/ReportBuilder/commit/ff9f83c6c2eb01ca155a59e386df25e1344beb77
