### ISSUE TITLE
Embedded reports broken in version 1.0

### ISSUE THREAD

**Issue by abaird** [rajatthareja/ReportBuilder#46]
After upgrading from 0.1.6 to 1.0, the embedded screenshots no longer display in the report. I'm using the following code to embed the images:
In hooks.rb -
```
After do |scenario|
  if !@settings.debug && scenario.failed? && !@browser.nil?
    encoded_image = @browser.screenshot.base64
    embed("data:image/png;base64,#{encoded_image}","image/png")
  end
end
```
In the report builder script file -
```
require 'report_builder'

html_report_name = ARGV[0]
app_id = ARGV[1]

ReportBuilder.configure do |config|
  config.json_path = '.'
  config.report_path = html_report_name.gsub(/\.html/,'')
  config.report_types = [:html]
  config.report_tabs = [:features, :scenarios, :errors]
  config.report_title = "title - #{app_id}"
end

ReportBuilder.build_report
```

When I get a set of files that I can upload without disclosing customer data I will.

**Comment by rajatthareja** [comment]
@abaird Thanks for reporting, Issue is fixed now. https://github.com/rajatthareja/ReportBuilder/commit/16de74f0a4ee59dcfa1dca205c249b1720a51dcc

@rockwig Please provide more details and raise a new issue.
