### ISSUE TITLE
tags dropdown in new version?

### ISSUE THREAD

**Issue by viyatgandhi** [rajatthareja/ReportBuilder#50]
![image](https://user-images.githubusercontent.com/13936567/31568766-e21b23dc-b03b-11e7-8cd1-432aba692040.png)

We had tags dropdown in old version - I think it was helpful to filter to view specific list of scenarios.  Any way to bring it back/enable in new version?

**Comment by rajatthareja** [comment]
https://github.com/rajatthareja/ReportBuilder/commit/e515633bdd86d2530dd19af257c6f4b89f7963c3
Now we can search and filter by tag in new UI
