### ISSUE TITLE
show time to execute in report

### ISSUE THREAD

**Issue by viyatgandhi** [rajatthareja/ReportBuilder#51]
![image](https://user-images.githubusercontent.com/13936567/31568855-5170c214-b03c-11e7-8fd1-b4ca305d6efb.png)

Time to execute on scenario and step level.
I think this was also an important feature - any way to bring it back or enable it in new version?

**Comment by mascolim** [comment]
#52

**Comment by rajatthareja** [comment]
![duration](https://user-images.githubusercontent.com/16877986/31851407-bc7fca9a-b682-11e7-9709-a9a4ae703f86.png)
