### ISSUE TITLE
tags search unavailable and table width inconsistent in new build 

### ISSUE THREAD

**Issue by viyatgandhi** [rajatthareja/ReportBuilder#57]
![image](https://user-images.githubusercontent.com/13936567/31973514-0ecb6708-b8ec-11e7-89db-f3a9c95094ca.png)

I think in latest build tag search option is no longer available and table width is also inconsistent while you click on pagination number. Report was fine until this commit 3b2507161ff8e4a1dd898bbfa638af83e2c3c963

**Comment by rajatthareja** [comment]
Tag search is working fine, Table width is fixed.

![table_width_fixed](https://user-images.githubusercontent.com/16877986/31999611-88c55c10-b9b1-11e7-9c2f-e6139bc2c485.png)

**Comment by viyatgandhi** [comment]
@rajatthareja thanks for the quick fix.  I thought tag search was missing because of the missing tag column in data table.
