### ISSUE TITLE
Retry file created '.retry' format

### ISSUE THREAD

**Issue by nekontachik** [rajatthareja/ReportBuilder#58]
My config in hooks.rb 
`config.retry_report_path = 'tmp/retry'`
 `config.report_types = [:html, :retry]`

String from readme for config
> json report output file path with file name without extension

After finishing tests I have file 'retry.retry', but i need '.txt' file for cucumber

**Comment by enkessler** [comment]
Cucumber doesn't care what extension the retry file has. As long as the file name that you give it exists, it will work. If you really want to, you could rename the file after it is created.
