### ISSUE TITLE
Is there a way to include attachments? Like .txt files?

### ISSUE THREAD

**Issue by reach2jeyan** [rajatthareja/ReportBuilder#59]
I love this report, far better than the pretty cucumber reports. I had want to know if there is a defined capability to include text attachments? like `include_images == true`?

**Comment by rajatthareja** [comment]
@reach2jeyan 

You can link your log file using cucumber embed() method like this:

embed('Logs Link Title|||http://myUrl/myLogFile', 'text/plain')
embed('Logs Link Title|||myLogFolder/myLogFile', 'text/plain')
or
embed('http://myUrl/myLogFile', 'text/plain')
embed("myLogFolder/myLogFile", "text/plain")
