### ISSUE TITLE
ScenarioOutput Data Requires Formatting

### ISSUE THREAD

**Issue by tk8817** [rajatthareja/ReportBuilder#6]
Hey @rajatthareja , 

I am testing the new release and I have been thinking of how we can handle formatting ScenarioOutput data. One thing I find interesting is that the newlines show up if you inspect the HTML source, but they do not show up in the report. 

I have made an album of images to show the issue in detail:
[Cucumber ReportBuilder Output JSON Formatting Issue](http://imgur.com/a/UKnzR)

- Image 1, how it looks in HTML Report
- Image 2, how it looks in Terminal
- Image 3, how it looks when inspecting the HTML element in chrome
- Image 4, how it looks in JSON

The \n are required for the terminal output and Cucumber directly writes whatever the Terminal receives into the JSON file. It would appear that we need to add a .gsub('\n', '< b r / >) when reading out this data from the JSON. I believe that would fix the issue. 

Let me know what you think, or if you have a better idea.

**Comment by rajatthareja** [comment]
@tk8817 
Added few gsub

```ruby
output.gsub("\n",'</br>').gsub("\t",'&nbsp;&nbsp;').gsub(' ','&nbsp;')
```

**Comment by tk8817** [comment]
@rajatthareja just checked out master and the data looks perfect now -- matches Terminal output 100%. This issue can be closed.
