### ISSUE TITLE
json report - result is overwritten and not appended

### ISSUE THREAD

**Issue by shivpandarge** [rajatthareja/ReportBuilder#62]
After running multiple features (in single run) only last feature result is retained in the report i.e. result is overwritten and not appended in json. Please note that we are using database truncation policy after each scenario.
Below for reference 
1) below in cucumber.yml - 
default: -f json -o features/reports/report<%= ENV['TEST_ENV_NUMBER'] %>.json -f html -o features/reports/my_test_report<%= ENV['TEST_ENV_NUMBER'] %>.html -f pretty
2) env.rb - attached 

Thanks in advance.

[env.txt](https://github.com/rajatthareja/ReportBuilder/files/1597320/env.txt)

**Comment by enkessler** [comment]
If you are running everything in one process, then I would not be surprised if `ENV['TEST_ENV_NUMBER']` never changed value and thus that file gets overwritten continuously.

`report_builder` only takes multiple data sets and combines them. It is not responsible for creating those data sets in the first place. What tools are you using to split up your test executions?
