### ISSUE TITLE
report path

### ISSUE THREAD

**Issue by Suganthi06** [rajatthareja/ReportBuilder#63]
When I use the code examples in my jruby project, the reports are getting generated successfully.
However, it is generated only at the project root directory and not in the path that I specify.

When I specify a particular path for the report to get generated, I see 
_**RuntimeError: Error:: No file(s) found at ...**_ (at the project root directory)

**Comment by rajatthareja** [comment]
@Suganthi06 
Please provide more details JRuby version, gem version, sample code etc...

**Comment by Suganthi06** [comment]
**JRuby version** - 9.1.15.0
**ReportBuilder gem version** - 1.4

**Code:**
at_exit do
  ReportBuilder.configure do |config|
    config.json_path = '<project_folder/reports_folder/>report'
    config.report_path = '<project_folder/reports_folder/>report'
    config.report_types = [:json, :html]
    config.report_title = 'Automation Test Results'
    config.include_images = false
  end
  ReportBuilder.build_report
end

_RuntimeError: Error:: No file(s) found at <project_folder/reports_folder/>report
       get_groups at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/report_builder-1.4/lib/report_builder/builder.rb:98
     build_report at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/report_builder-1.4/lib/report_builder/builder.rb:28
     build_report at C:/jruby-9.1.15.0/lib/ruby/gems/shared/gems/report_builder-1.4/lib/report_builder.rb:61_

**Comment by rajatthareja** [comment]
> config.json_path = '<project_folder/reports_folder/>report'

Your JSON report files generated by cucumber are in '<project_folder/reports_folder/>report' ?

**Comment by Suganthi06** [comment]
JSON and HTML report gives me the same error if I change the path.

**Comment by rajatthareja** [comment]
@Suganthi06
> config.json_path

is input JSON path not output JSON path.

**Comment by Suganthi06** [comment]
input json file is also throwing the same error if i change the path. if i don't change the path, html is not finding the json that has been created in '<project_folder/>report.json'

**Comment by rajatthareja** [comment]
Try this
```
config.json_path = '<project_folder/>report'
config.report_path = '<project_folder/reports_folder/>report'
```

**Comment by Suganthi06** [comment]
Thank you ! This may work (I haven't tried) But I want all reports in the same report folder. I can try without 'json_path' line itself.

**Comment by Suganthi06** [comment]
Any updates?
