### ISSUE TITLE
additional_js evaluates to true and not path

### ISSUE THREAD

**Issue by colintsteele** [rajatthareja/ReportBuilder#64]
When trying to use the Additional JS option with `--js` in command line, I am given the error message `no implicit conversion of true to String`.  After placing a binding inside of the `bin/report_builder` it seems apparent that the block arguments given to any of the additional options are true if an option flag is given in the CLI, but no actual value is being passed in.

**Comment by rajatthareja** [comment]
@colintsteele Thanks for the fix. It's Merged.
