### ISSUE TITLE
Output in the reports

### ISSUE THREAD

**Issue by reach2jeyan** [rajatthareja/ReportBuilder#66]
There are instances where we need to publish the output with `puts` and in such cases, cucumber prints the output in the cucumber reports.

Is there a way to do that in report_builder? capture whatever printed in the terminal?

**Comment by enkessler** [comment]
> cucumber prints the output in the cucumber reports

What do you mean by that?

**Comment by rajatthareja** [comment]
@reach2jeyan ReportBuilder already supports puts output.

See in [Sample Report](http://reportbuilder.rajatthareja.com/sample/report.html) 
Feature: I am some feature for testing some functionality
Scenario: I am some testing scenario of some functionality

**Comment by reach2jeyan** [comment]
@rajatthareja Yes I see that! Weird, I was trying to print the output of a file and the same was not getting reflected under the steps.

Thanks for clarifying, will check it again!
