### ISSUE TITLE
If tags are added at the example levels for scenario outline, then those examples are not reported in the html report

### ISSUE THREAD

**Issue by chhatbarjignesh** [rajatthareja/ReportBuilder#69]
If tags are added at the example levels for scenario outline, then those examples are not reported in the html report

   ```
@tag1
    Scenario Outline: Breaker joins a game
    Given the Maker has started a game with the word "<word>"
    When the Breaker joins the Maker's game
    Then the Breaker must guess a word with 5 characters
 
    @smoke @qa_only
    Examples:
      | word     |
      | silky    |
   Examples:
      | word     |
      | second   |
      | third    |
```
if you run the above scenario and generate the report it will generate only three scenario in report and from that three it will say two are duplicate with (X2) added in scenario description

**Comment by chhatbarjignesh** [comment]
I have fix for this in the forked branched, i just change the group by id to line as id was being duplicated while adding tags at example level, probably defect in cucumber reporting

**Comment by sandeepnagra** [comment]
@rajatthareja - Can we get this fix merged?

**Comment by chhatbarjignesh** [comment]
I have created the [https://github.com/rajatthareja/ReportBuilder/pull/70](url). for this issue. I have also added one small functionality as an enhancement where now it will also support the embeddings if the embeddings are being made as `text/html` in before hooks

**Comment by rajatthareja** [comment]
@chhatbarjignesh Thank you for reporting the issue.

**Comment by rajatthareja** [comment]
Fixed https://github.com/rajatthareja/ReportBuilder/commit/d4e93a32c89986c39c5d00149a8c36145f8836e6

**Comment by chhatbarjignesh** [comment]
Thank you @rajatthareja
