### ISSUE TITLE
Added section for filtering Tags on Summary page.

### ISSUE THREAD

**Issue by jflohre** [rajatthareja/ReportBuilder#73]
Is there already a way to create a section like below?
![image](https://user-images.githubusercontent.com/2693827/46691458-fc398980-cbd2-11e8-8c61-014abe8a788c.png)

We have scenarios that have certain tags(that start with acauto_) that we would like to show up in the report.  I found out how to do this and was thinking about making a pull request for this.  Basically passing in an option and if that option is true to show the column and if a filter is provided than filter that tags.

Is this possible already?

Thank you

**Comment by rajatthareja** [comment]
@jflohre Search by tag is already enabled, although the Tags column is hidden.

**Comment by jflohre** [comment]
This would be mainly to show the tags, and not just a search.  The goal would be to easily grab tags from failing test so that my team can easily look into them.  

I have the code for this and just need to create a pull request for it. (Then you can take a look and approve/deny it if you don't mind?)

**Comment by rajatthareja** [comment]
All contributions are greatly appreciated. Feel free to create a pull request.
