### ISSUE TITLE
Cucumber Steps with "double quotes"/"<>"  is broken and converted to ASCII codes

### ISSUE THREAD

**Issue by prashanth-sams** [rajatthareja/ReportBuilder#76]
The JSON file generated through report builder interprets the special characters such as "", <>, "<>"

![regex_2](https://user-images.githubusercontent.com/2948696/48469943-7def8900-e809-11e8-8ba6-ab62071b66dc.jpg)

![regex](https://user-images.githubusercontent.com/2948696/48469694-f86bd900-e808-11e8-81c9-57afb717a7fc.jpg)

**Comment by prashanth-sams** [comment]
@rajatthareja is there something we can do here?

**Comment by rajatthareja** [comment]
@prashanth-sams I will try to fix it on coming weekend. Can u try couple of old versions of gem and let me know if it's working fine in any of them.

**Comment by rajatthareja** [comment]
![my test results](https://user-images.githubusercontent.com/16877986/49337359-491c6800-f638-11e8-8e3b-7e4771d9af77.png)

https://reportbuilder.rajatthareja.com/sample/report.html

@prashanth-sams 
"double quotes" are working fine for me, If you are still facing issue please provide more details, cucumber version, ruby version, OS
