### ISSUE TITLE
No CSS and JS without internet connection

### ISSUE THREAD

**Issue by yaxartes** [rajatthareja/ReportBuilder#78]
Hello!

I'm trying to use your gem to form a report for my tests in jenkins build.
The problem is the internet access is limited for our work intranet. As a result all the styles and js code is unavailable in the report.

Is it possible to include CSS/JS files in the gem to install?

P.S. Sorry for a bit messy question, I'm not really a frontend person.

**Comment by chhatbarjignesh** [comment]
Hi @yaxartes,

there are couple of ways to do that its basically that Jenkins security feature that not allow to access certain sources. you can write a custom exception in jenkins to allow an access to those resources.

For example something like this.
`System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "sandbox allow-same-origin allow-scripts; script-src * 'unsafe-inline'; img-src * 'self' data: https:; style-src * 'unsafe-inline'; font-src *");`

another option is to download the CSS and JS from the repo and upload to where your jenkins can access then fork this gem and modify some of the erb files where there is a reference of the CSS and JS and update that reference to where you put the CSS and JS and continue using the forked gem.

I would strongly suggest the first option.

Hope this helps

**Comment by yaxartes** [comment]
This is not really a Jenkins issue, actually it is our network security issue (I work in a bank), because I have the same problem on my own local machine. 
Thank you for the advice, I will try to figure out something.
