### ISSUE TITLE
Duplicate result handling is undefined behavior

### ISSUE THREAD

**Issue by enkessler** [rajatthareja/ReportBuilder#80]
When merging JSON files with overlapping test results (e.g. the output of a run and the output of running just the failures from the previous run), only one result for each test is included in the merged result. Looking at the tests, this seems intentional. However, there is no indication of why this is desired or which of the several results for a given test will take precedence. Is it the most current result by time? Most current result based on the order that they are passed to the builder? Does it take a passing result over a failing result?

I've tried passing the input files in in different orders and it doesn't seem to make a difference. Although, coincidentally, my particular use case is to only get one result for a given test, I can't rely on the result of this gem if I don't know why/how I only get one result.

So...how does this work?

**Comment by rajatthareja** [comment]
feature['elements'] = feature['elements'].group_by do |scenario|
          scenario['id'] + scenario['line'].to_s
        end.values.map do |scenario_group|
          the_scenario = scenario_group.find do |scenario|
            scenario['status'] == 'passed'
          end || scenario_group.first
          if scenario_group.size > 1
            the_scenario['name'] += " (x#{scenario_group.size})"
          end
          the_scenario

It takes the passed run if non passed it takes the first run.

**Comment by rajatthareja** [comment]
We have option to create group report as well if we are running same scenario in different environments

ReportBuilder.configure do |config|
     config.input_path = {
      'Group A' => ['path/of/json/files/dir1', 'path/of/json/files/dir2'],
      'Group B' => ['path/of/json/file1', 'path/of/json/file2'],
      'Group C' => 'path/of/json/files/dir'}
  end

ReportBuilder.build_report

**Comment by enkessler** [comment]
> We have option to create group report as well if we are running same scenario in different environments

I do use the grouping mechanism to generate a report that shows all 3 runs (the initial run, the run of the failures from the 1st run, and the run of the failures from the 2nd run). It's a pretty handy feature. :)

But I also then generate a report that is consolidated to have a single, final result for each test (because managers don't need the multi-run breakdown, they just need a final yes/no).

> It takes the passed run if non passed it takes the first run.

So, basically, it ignores duplicate results unless the duplicate is a pass and the original is a fail? That's not quite what I need.

If we think of combining JSON results like merging hashes, the current behavior is like `Hash#reverse_merge` instead of `Hash#merge`. This would be manageable by simply reversing the order that I merge in result sets but that extra special case of the algorithm preferring passes over failures takes control entirely out of my (read: the user's) hands.

I think that it can still work in my case if I combine the JSON in reverse order that I ran them. I don't bother to run passing tests additional times, so a passing result is also the most recent result and, for a failing result, the 'first' result that I combine is actually the final result. Still, it'd be nice if it worked more intuitively and I didn't have to do things backwards.

Thanks for the information!

**Comment by rajatthareja** [comment]
Changed to last
