### ISSUE TITLE
Access to un-minified CSS for use in development

### ISSUE THREAD

**Issue by tk8817** [rajatthareja/ReportBuilder#9]
Hey @rajatthareja , I am working on cleaning up the HTML report styling but it is tough with the minified-css. Any chance you can provide me with the full css files. 

I have an completed feature branch for one main item (styling H3's instead of spans), but will need the css files to move span broken/passed styling to h3 , and remove existing H3 styles. 

Here is a screenshot of what it looks likes when it is fully working (I injected the CSS live in chrome, based on the styles generated in my feature branch)

![New H3 Styling](http://i.imgur.com/VmesQcM.png)

**Comment by rajatthareja** [comment]
@tk8817 Hope following will be helpful ....

* [JQuery UI CSS Theam Used in ReportBuilder](http://jqueryui.com/themeroller/?ffDefault=Arial%2CHelvetica%2Csans-serif&fsDefault=1em&fwDefault=normal&cornerRadius=3px&bgColorHeader=e9e9e9&bgTextureHeader=flat&borderColorHeader=dddddd&fcHeader=333333&iconColorHeader=444444&bgColorContent=ffffff&bgTextureContent=flat&borderColorContent=dddddd&fcContent=333333&iconColorContent=444444&bgColorDefault=f6f6f6&bgTextureDefault=flat&borderColorDefault=c5c5c5&fcDefault=454545&iconColorDefault=777777&bgColorHover=ededed&bgTextureHover=flat&borderColorHover=cccccc&fcHover=2b2b2b&iconColorHover=555555&bgColorActive=007fff&bgTextureActive=flat&borderColorActive=003eff&fcActive=ffffff&iconColorActive=ffffff&bgColorHighlight=fffa90&bgTextureHighlight=flat&borderColorHighlight=dad55e&fcHighlight=777620&iconColorHighlight=777620&bgColorError=fddfdf&bgTextureError=flat&borderColorError=f1a899&fcError=5f3f3f&iconColorError=cc0000&bgColorOverlay=aaaaaa&bgTextureOverlay=flat&bgImgOpacityOverlay=0&opacityOverlay=30&bgColorShadow=666666&bgTextureShadow=flat&bgImgOpacityShadow=0&opacityShadow=30&thicknessShadow=5px&offsetTopShadow=0px&offsetLeftShadow=0px&cornerRadiusShadow=8px)
Includes: core.css, accordion.css, tabs.css, theme.css
[CSS File](https://raw.githubusercontent.com/rajatthareja/ReportBuilder/master/vendor/assets/stylesheets/jquery-ui.min.css)

* FYI [CSS Unpacker](http://cssunpacker.com/)

**Comment by tk8817** [comment]
Thanks @rajatthareja , I have not used minifiers for CSS before, cool stuff. I have everything i need now, expect a pull request soon.
