### ISSUE TITLE
Question about Scenario count

### ISSUE THREAD

**Issue by nerrante** [rajatthareja/ReportBuilder#90]
This is probably obvious but I wanted to double check - am I correct that the scenario count includes the number of scenarios in the scenario outline?  So for example, if I have:

Scenario Outline:
*code here*

Scenarios:
*example 1*
*example 2*

That would count as 2 scenarios, not 1?

**Comment by rajatthareja** [comment]
Yes it will count as 2

See https://reportbuilder.rajatthareja.com/sample/report.html
